### ISSUE TITLE
placing order doesn't work

### ISSUE THREAD

**Issue by niranjanshr13** [MeheLLC/Robinhood#9]
placing order doesn't work.
place_buy_order <-- this module doesn't work; and 
what is a unquote module; there isn't no definition about it.

**Comment by Jamonek** [comment]
I'll review this in a few.

**Comment by jsmwoolf** [comment]
Hi niranjanshr13,

The code was written with some Python 2.  I just issued a pull request that would make the code Python 3 compliant.  That should allow place_buy_order to work properly.

**Comment by niranjanshr13** [comment]
@jsmwoolf thank's just followed the README.md; worked perfectly.

**Comment by jsmwoolf** [comment]
@niranjanshr13: You're welcome.
